reset_to_98​(​int​ *n); 
 swap_int​(​int​ *a, ​int​ *b); 
 _strlen​(​char​ *s); 
 _puts​(​char​ *str); 
 print_rev​(​char​ *s); 
 rev_string​(​char​ *s); 
 puts2​(​char​ *str); 
 puts_half​(​char​ *str); 
 print_array​(​int​ *a, ​int​ n); 
 *​_strcpy​(​char​ *dest, ​char​ *src); 
 _atoi​(​char​ *s);
